### ISSUE TITLE
BIP70 problem: "Wrong signature"

### ISSUE THREAD

**Issue by imaginaryusername** [bitcoincash-wallet/bitcoincash-wallet#16]
Hi,

I tried to scan a Bitpay payment request, but the payment failed as follows:

![screenshot_2018-04-22-07-31-18](https://user-images.githubusercontent.com/34949601/39096180-525edc28-4601-11e8-83bb-c500795e76c2.png)

**Comment by snapfractalpop** [comment]
Are you using the Playstore version, or did you compile from source? You can follow this issue here: https://github.com/bitcoincash-wallet/bitcoincash-wallet/issues/13. I submitted a PR, which was merged manually, but just *after* the last release. Here are the relevant commits: ae9758cb069e2195e73c5a0e240a03d12d68fb39 and 5efa3552669c2c844c7bd34c4d4d6734490fb592. If you built it yourself from source, you can patch with these. If you installed from Playstore, I believe you will have to wait until the next release.

**Comment by HashEngineering** [comment]
I will try to release a new version soon, I forgot that there were updates that were not included in the current version.

**Comment by clxcoltz** [comment]
Got it, I'll wait for the release then. 

On a side note, it'll also be super nice if full cashaddr support (as in #10 ) is there for the next release. Then I can really start recommending to people. =)

**Comment by HashEngineering** [comment]
I am about to release v5.39.3 to google play.  

This version here will also install over the Google Play version 5.39.2:
https://github.com/bitcoincash-wallet/bitcoincash-wallet/releases/tag/v5.39.3

**Comment by imaginaryusername** [comment]
Awesome! Don't see it at Google Play yet, but hopefully soon.

**Comment by imaginaryusername** [comment]
Been a week and still didn't see it pushed, don't know about how the Play Store push things... anything I can check?

**Comment by HashEngineering** [comment]
We are at 75% on the rollout (though only about 30% have upgraded).  The reason for the slow roll out is to look for new bugs that might be created by the update.  So far we haven't seen any.  The rollout will be complete in a few days and it will be available to you.

**Comment by imaginaryusername** [comment]
Just tested it, works very well! Do you have an address I can tip to, per chance?

**Comment by HashEngineering** [comment]
here is my BCH address:  14BX5hcxAaX6nWenZrXFbmWU7Jsan4m9y3

Thank you.

**Comment by imaginaryusername** [comment]
Seems fixed now!
